Add container helpers
balena-os/leviathan pull request #373
Opened 2021-03-26 08:17 UTC by rcooke-warwick

2021-03-26 21:16 UTC, Bucknalla requested changes
Docs updates/improvements are great! Really improves the onboarding and explains leviathan in coherent manner. Just a couple comments + probably worth squashing to tidy up what's docs vs code changes.

2021-03-26 21:16 UTC, Bucknalla commented on core/Dockerfile.template
> +#RUN wget https://github.com/balena-io/balena-cli/releases/download/v11.7.0/balena-cli-v11.7.0-linux-x64-standalone.zip && unzip balena-cli-v11.7.0-linux-x64-standalone.zip
If these are commented out now, do we still need them in here?

2021-03-26 21:16 UTC, Bucknalla commented on core/Dockerfile.template
> +#RUN ln -sf $(pwd)/balena-cli/balena /usr/local/bin/balena
Same as previous comment about commented out code

2021-04-07 08:12 UTC, rcooke-warwick commented
@vipulgupta2048 tidied this up, I think we should be able to merge

2021-04-07 10:52 UTC, vipulgupta2048 reviewed
LGTM

2021-04-07 14:08 UTC, Bucknalla approved these changes
LGTM

2021-04-07 14:08 UTC, merged