Add unstable property to quickstart docs
balena-os/leviathan pull request #843
Opened 2022-11-15 10:58 UTC by vipulgupta2048

Solves #841

- patch: Add debug: unstable to docs
- Make always-fail error more descriptive

2022-11-15 12:44 UTC, lmbarros requested changes
Thanks, Vipul! I spotted a small typo, but otherwise it's good to merge IMO!

2022-11-15 12:44 UTC, lmbarros commented on suites/e2e/tests/always-fail/index.js
> +          `This test should have been skipped in the first place but didn't. Add this test to the unstable list avaiable in the debug object in config.js. Refer to debugging docs or test code for mor
```suggestion
          `This test should have been skipped in the first place but didn't. Add this test to the unstable list available in the debug object in config.js. Refer to debugging docs or test code for more information.`,
```

2022-11-15 18:54 UTC, vipulgupta2048 commented
@lmbarros resolved, please re-review

2022-11-15 18:57 UTC, lmbarros approved these changes
:rocket:

2022-11-28 08:18 UTC, vipulgupta2048 commented
@balena-ci rebase

2022-11-29 11:24 UTC, vipulgupta2048 commented
@balena-ci I self-certify!

2022-11-29 11:25 UTC, vipulgupta2048 commented
The bulldozer maybe undergoing an outage so merging it myself.

2022-11-29 11:25 UTC, merged